pipeline {
  agent {
    kubernetes {
      yamlFile 'kubernetes-plugin/KubernetesPod.yaml'
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
        }
        container('busybox') {
          sh '/bin/busybox'
        }
      }
    }
    stage('Snyk image') {
      steps {
        container('snyk') {
          sh 'snyk --help'
          sh 'pwd && ls -al'
        }
      }
    }
  }
}
